# C/C++
[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = [
  "--style={BasedOnStyle: Google}",
] }

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format", args = [
  "--style={BasedOnStyle: Google}",
] }

# TOML
[[language]]
name = "toml"
auto-format = true
roots = ["."]

# NIX
[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

# RUST
[language-server.rust-analyzer.config]
check.command = "clippy"

# VERILOG
[language-server.verible-verilog-ls]
command = "verible-verilog-ls"

[[language]]
name = "verilog"
auto-format = true
language-servers = ["verible-verilog-ls"]
